// Mock data for Gundam collection
export const getMockData = () => {
    return [
        {
            id: 1,
            name: "RX-78-2 Gundam",
            series: "Mobile Suit Gundam",
            grade: "Real Grade",
            scale: "1/144",
            price: 850000,
            image: "/api/placeholder/300/300",
            seller: "GundamShop",
            purchaseDate: "15/03/2023",
            condition: "Đã lắp ráp",
            description: "Mô hình RX-78-2 Gundam từ series Mobile Suit Gundam đầu tiên. Mô hình Real Grade với chi tiết cao."
        },
        {
            id: 2,
            name: "Wing Gundam Zero EW",
            series: "Gundam Wing",
            grade: "Master Grade",
            scale: "1/100",
            price: 1200000,
            image: "/api/placeholder/300/300",
            seller: "ModelKing",
            purchaseDate: "22/05/2023",
            condition: "Mới nguyên hộp",
            description: "Wing Gundam Zero Custom từ phim Endless Waltz. Phiên bản Master Grade với cánh thiên thần đẹp mắt."
        },
        {
            id: 3,
            name: "Unicorn Gundam",
            series: "Gundam Unicorn",
            grade: "Perfect Grade",
            scale: "1/60",
            price: 4500000,
            image: "/api/placeholder/300/300",
            seller: "PlasticModel",
            purchaseDate: "07/01/2024",
            condition: "Mới nguyên hộp",
            description: "Perfect Grade Unicorn Gundam với hệ thống LED và khả năng chuyển đổi giữa Unicorn Mode và Destroy Mode."
        },
        {
            id: 4,
            name: "Freedom Gundam",
            series: "Gundam SEED",
            grade: "Master Grade",
            scale: "1/100",
            price: 1300000,
            image: "/api/placeholder/300/300",
            seller: "AnimeToy",
            purchaseDate: "14/09/2023",
            condition: "Đã lắp ráp",
            description: "Master Grade Freedom Gundam từ series Gundam SEED. Mô hình có khả năng tạo dáng linh hoạt."
        },
        {
            id: 5,
            name: "Zaku II",
            series: "Mobile Suit Gundam",
            grade: "High Grade",
            scale: "1/144",
            price: 450000,
            image: "/api/placeholder/300/300",
            seller: "GundamVN",
            purchaseDate: "30/11/2023",
            condition: "Mới nguyên hộp",
            description: "High Grade MS-06 Zaku II, mobile suit tiêu biểu của Principality of Zeon."
        },
        {
            id: 6,
            name: "Strike Freedom Gundam",
            series: "Gundam SEED Destiny",
            grade: "Real Grade",
            scale: "1/144",
            price: 980000,
            image: "/api/placeholder/300/300",
            seller: "HobbyStore",
            purchaseDate: "19/02/2024",
            condition: "Đã lắp ráp",
            description: "Real Grade Strike Freedom Gundam với full dragoon system và chi tiết mạ vàng."
        },
        {
            id: 7,
            name: "Barbatos Lupus Rex",
            series: "Gundam Iron-Blooded Orphans",
            grade: "High Grade",
            scale: "1/144",
            price: 520000,
            image: "/api/placeholder/300/300",
            seller: "IronBlood",
            purchaseDate: "25/05/2023",
            condition: "Mới nguyên hộp",
            description: "Gundam Barbatos Lupus Rex từ Iron-Blooded Orphans với thiết kế hoang dã và vũ khí mace độc đáo."
        },
        {
            id: 8,
            name: "Nu Gundam",
            series: "Char's Counterattack",
            grade: "Real Grade",
            scale: "1/144",
            price: 890000,
            image: "/api/placeholder/300/300",
            seller: "GundamMaster",
            purchaseDate: "02/04/2023",
            condition: "Đã lắp ráp",
            description: "Real Grade Nu Gundam từ Char's Counterattack với hệ thống fin funnel ấn tượng."
        },
        {
            id: 9,
            name: "SD Sangoku Soketsuden Zhao Yun 00 Gundam",
            series: "SD Sangoku Soketsuden",
            grade: "Super Deformed",
            scale: "SD",
            price: 320000,
            image: "/api/placeholder/300/300",
            seller: "SDWorld",
            purchaseDate: "05/12/2023",
            condition: "Mới nguyên hộp",
            description: "SD Sangoku Soketsuden Zhao Yun 00 Gundam với thiết kế chibi dễ thương kết hợp phong cách Tam Quốc."
        },
        {
            id: 10,
            name: "RX-78-2 Gundam",
            series: "Mobile Suit Gundam",
            grade: "Entry Grade",
            scale: "1/144",
            price: 250000,
            image: "/api/placeholder/300/300",
            seller: "BeginnerModel",
            purchaseDate: "18/08/2023",
            condition: "Đã lắp ráp",
            description: "Entry Grade RX-78-2 Gundam dành cho người mới bắt đầu, dễ lắp ráp nhưng vẫn giữ được dáng vẻ chuẩn xác."
        },
        {
            id: 11,
            name: "SD Ex-Standard Wing Gundam Zero EW",
            series: "Gundam Wing",
            grade: "Super Deformed",
            scale: "SD",
            price: 280000,
            image: "/api/placeholder/300/300",
            seller: "SDMaster",
            purchaseDate: "12/03/2024",
            condition: "Mới nguyên hộp",
            description: "SD Ex-Standard Wing Gundam Zero EW với phong cách chibi cute, phiên bản thu nhỏ từ Gundam Wing Endless Waltz."
        },
        {
            id: 12,
            name: "Core Gundam & Marsfour Unit",
            series: "Gundam Build Divers Re:Rise",
            grade: "Entry Grade",
            scale: "1/144",
            price: 280000,
            image: "/api/placeholder/300/300",
            seller: "BuilderShop",
            purchaseDate: "30/04/2024",
            condition: "Mới nguyên hộp",
            description: "Entry Grade Core Gundam với Marsfour Unit từ series Gundam Build Divers Re:Rise. Thiết kế đơn giản nhưng đẹp mắt."
        }
    ];
};